Add mock interface + fix potential data race
ThomasObenaus/go-base pull request #35
Opened 2024-06-27 15:43 UTC by maxZ-2020

- add mock interface for shutdown.Handler
- fix potential data race

2024-06-27 16:18 UTC, ThomasObenaus requested changes
The project does not build any more with the added changes.

`make` gives me
![image](https://github.com/ThomasObenaus/go-base/assets/1695514/d3df5a96-618d-4772-a53e-5c6b1452504e)

2024-06-28 07:41 UTC, ThomasObenaus commented on test/mocks/shutdown/mock_shutdownHandler.go
it is better practice to call the mocks <....>_test.go to avoid that they are packaged in the application binary

2024-06-28 07:42 UTC, ThomasObenaus commented on test/mocks/shutdown/mock_shutdownHandler.go
in general who consumes this mock?

2024-06-28 09:01 UTC, maxZ-2020 commented
Adjusted Scope as requested

2024-06-28 09:36 UTC, ThomasObenaus approved these changes

2024-06-28 09:42 UTC, merged